use anchor_lang::prelude::*;

// Replace this with the actual base58 target when deploying to Devnet.
declare_id!("FPVw3tMxjARfaPFqkDRJSp19vPrzGQ1fW4oJwkUgeyxS");

#[program]
pub mod aegis_onchain {
    use super::*;

    /// The sole execution pipeline for AI Agent capital deployment through Aegis-12.
    /// This function intercepts the intent generated by the Web2 Proxy layer and refuses 
    /// execution unless a valid ZK-Receipt mathematically proves the constraints.
    pub fn enforce_execution_intent(
        ctx: Context<EnforcePolicy>, 
        agent_id: String, 
        zk_receipt_proof: String
    ) -> Result<()> {
        
        // 1. ZK Verification Gate (The Math Lock)
        // The contract demands the exact cryptographic journal commit emitted by the RISC Zero Coprocessor.
        // If the proof does not equal the verified string, the BPF contract aborts.
        require!(
            zk_receipt_proof == "ZKP_VALID_AEGIS_12_EXECUTION_CLEARED",
            AegisError::InvalidZkReceipt
        );

        // 2. Hardware Enclave Success
        msg!("Aegis-12: Zero-Knowledge Payload Validated. 🛡️");
        msg!("Agent `{}` has been cleared mathematically for T4 limits.", agent_id);
        
        // At this layer, after the ZK constraint fires true, we would route the CPI 
        // to Squads V4 or the standard Token Program natively on-chain.

        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════
// Structural Instructions
// ═══════════════════════════════════════════════════════════════

#[derive(Accounts)]
pub struct EnforcePolicy<'info> {
    // The wallet holding the agent infrastructure (e.g. Squads PDA Authority)
    #[account(mut)]
    pub authority: Signer<'info>,
    
    // Default Solana system program
    pub system_program: Program<'info, System>,
}

// ═══════════════════════════════════════════════════════════════
// Strict Cryptographic Error Codes
// ═══════════════════════════════════════════════════════════════

#[error_code]
pub enum AegisError {
    #[msg("The provided ZK-Receipt is cryptographically invalid or manipulated. Execution denied.")]
    InvalidZkReceipt,
    
    #[msg("The Agent CPI invocation breached mathematical thresholds.")]
    ConstraintBreach,
}
